### ISSUE TITLE
No change in treated files with no functional changes

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [hakancelik96/unimport#106]
I don't know if the title is super clear, but in pylint the file `/tests/functional/a/abstract_abc_methods.py` is changed entirely after running unimport on it. The `git diff` is then the whole file and there is no change with `git diff --word-diff`.

Maybe the end of line are changed to something else ? Or the encoding is changed?

It's testable by doing `pre-commit install;pre-commit run unimport --all-files` on https://github.com/Pierre-Sassoulas/pylint/commit/314061e5ae5484c6f41d2ef1b506d08482fa74d3

**Comment by hakancelik96** [comment]
Thanks, I fixed it
