### ISSUE TITLE
Imports used in strings passed to typing functions

### ISSUE THREAD

**Issue by The-Compiler** [hakancelik96/unimport#126]
With something like:

```python
import typing
if typing.TYPE_CHECKING:
    from PyQt5.QtWebEngineWidgets import QWebEngineHistory
    from PyQt5.QtWebKit import QWebHistory

HistoryType = typing.Union['QWebEngineHistory', 'QWebHistory']
```

unimport thinks those imports are unused despite that not being the case. They're imported like this because they might be unavailable at runtime (only one of both is required for the application).

The same thing also happens in other places `typing` can take a type annotation as string, such as `typing.cast`, `typing.Callable` and probably more.

**Comment by hakancelik96** [comment]
Oh yeah, we didn't even think about creating new types like this. We support type comment, variable annotation, and type annotation as string but this is new.  I'm gonna try to add this as soon as I can. Thanks!

**Comment by The-Compiler** [comment]
As another example: `some_value = typing.cast('QWebHistory', None)` would lead to the same issue.
