### ISSUE TITLE
Multiline imports, `# unimport:skip` comments, and isort formatting

### ISSUE THREAD

**Issue by jparise** [hakancelik96/unimport#132]
`isort` (version 5.5.4) wants to relocate the `# unimport:skip` comments to a place where `unimport` doesn't recognize them.

### Before isort (works)

```py
from package import (  # unimport:skip
    module
)
```

### After isort (doesn't work)

```py
from package import (
    module
)  # unimport:skip
```

I'm starting with this project to ask if it's possible for `unimport` to recognize comments in this alternate formatting layout.

**Comment by hakancelik96** [comment]
Nodes from ast in py3.6 and py37 do not have col_offset, end_lineno, end_col_offset attributes, so it does not seem possible, but it seems possible thanks to the [get_source_segment](https://github.com/python/cpython/blob/3.8/Lib/ast.py#L2989) function and these attributes in py3.8.

I will send a PR

**Comment by hakancelik96** [comment]
No, my fault. I forgot that AST was ignoring whitespace and comment I couldn't find any result, I'll keep trying.
