### ISSUE TITLE
Support Python3.9 officially.

### ISSUE THREAD

**Issue by hadialqattan** [hakancelik96/unimport#135]
Hi, @hakancelik96, I think it's a good time to support Python3.9 officially.
Please see: https://www.python.org/downloads/release/python-390/

If you agree with me, please assign this issue to me. Have a nice day!

**Comment by hadialqattan** [comment]
@hakancelik96 
What about [PEP 617 -- New PEG parser for CPython](https://www.python.org/dev/peps/pep-0617/) and LibCST?

**Comment by hadialqattan** [comment]
@hakancelik96 We have no problem with Python3.9, but we do have with Python3.10! 

https://www.python.org/dev/peps/pep-0617/#migration-plan

**Comment by hakancelik96** [comment]
Libcst now supports 3.6, 3.7, 3.8 versions, we need to write our own refactoring code (I'm working on it now) Also did you look at this issue #26.

**Comment by hadialqattan** [comment]
Oh, yeah.

**Comment by hadialqattan** [comment]
BWT, I think #100 should be closed when you wrote your new refactoring method!
