### ISSUE TITLE
[BUG] normal import use case is considered as unused (only on master branch).

### ISSUE THREAD

**Issue by hadialqattan** [hakancelik96/unimport#144]
/`lab.py`:
```python
from pathlib import Path

EXAMPLE = Path(__file__).parent
```

---
```console
python3 -m unimport lab.py -d
```
```diff
--- lab.py

+++ 

@@ -1,3 +1,2 @@

-from pathlib import Path
 
 EXAMPLE = Path(__file__).parent
```

---
*Note: this bug doesn't affect the current version, only the master one!*

**Comment by hakancelik96** [comment]
[This is the line](https://github.com/hakancelik96/unimport/commit/b8bff1650e638913e91b99b9edc1c3cd142e4e5b#diff-4bcf6eec194e45ef0621a4c1183ba42878193e8529cac8edbbe17d4dd172f986R143) that caused the issue, I would appreciate it if you want to work on this issue, If you don't want it, I will.

**Comment by hadialqattan** [comment]
I'm gonna try as soon as I have time for that, and please don't forget to not release until we fix this!

**Comment by hadialqattan** [comment]
@hakancelik96 I'm sorry to say that, but unfortunately, I've no time for that, so I'm gonna unassign myself.

*I apologize for the delay and withdrawal.*

**Comment by hadialqattan** [comment]
I'm afraid to disrupt the workflow.

**Comment by hakancelik96** [comment]
Okey no problem
