### ISSUE TITLE
Bug where noqa or unimport:skip is ignored

### ISSUE THREAD

**Issue by jgillard** [hakancelik96/unimport#146]
I've found an issue with `# noqa` and `# unimport:skip` handling with `v0.6.6`. I don't get this issue with `v0.3.0`.

The snippet below works as expected:

```python
import math
import collections  # noqa
```

```diff
--- foo.py

+++ 

@@ -1,2 +1 @@

-import math
 import collections  # noqa
```

As soon as a newline is introduced between those two imports then the diff changes incorrectly:

```python
import math

import collections  # noqa
```

```diff
--- foo.py

+++ 

@@ -1,3 +1 @@

-import math
 
-import collections  # noqa
```

**Comment by hakancelik96** [comment]
Hi, thank you!

This bug only exists in python3.8, I'll fix it soon.
