### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by apelliciari** [hakancelik96/unimport#148]
Hi, 

very interesting project! 

I have this issue running it on my codebase (Python 3.8.5 + Django 3.0.3):

![image](https://user-images.githubusercontent.com/1625969/100441423-ba1b7c80-30a6-11eb-9e6c-6fff733b4401.png)

how can I provide you more information about it so you can tell me how to fix it? I didn't found a verbose option

Thanks

**Comment by hakancelik96** [comment]
Hi thank you.
It has already been solved by @isik-kaplan, I will examine and merge it.

**Comment by apelliciari** [comment]
Cool, thanks!!
