### ISSUE TITLE
Codecov check random fails

### ISSUE THREAD

**Issue by isidentical** [hakancelik96/unimport#156]
It really looks weird, and from an outsider's perspective seeing the latest commit to the repo as "FAILED" isn't that great. I have never seen any case where Codecov helped us in anything, so let's just remove it and use coverage locally!

**Comment by hakancelik96** [comment]
https://github.com/hakancelik96/unimport/commit/a11db72e724a9c47e5f99bbd7e04d44a6e319c6d#diff-2b2bda0c32d4aa698c35a605120c7745c3433d4ad4210996bfc7f32e9fe9f078R7
