### ISSUE TITLE
Python 3 f string usage provides false positive

### ISSUE THREAD

**Issue by miketheman** [hakancelik96/unimport#165]
Example `foo.py`:

```python
import os

print(f'{os.name} is the OS name')
```

```shell
$ unimport foo.py
os at foo.py:1
```

`os` is currently in use, but isn't being identified as so.

**Comment by furkanonder** [comment]
Hi @miketheman,
I think this problem existed in older versions. In Unimport's version 0.7.1, there are no warnings for `foo.py`.

**Comment by miketheman** [comment]
Hi @furkanonder !
Thanks for checking.

I tried to make sure I was using the most recent version:

```console
$ unimport --version
Unimport 0.7.1

**Comment by furkanonder** [comment]
```
furkan@archlinux ~$ cat foo.py                                   
import os

print(f'{os.name} is the OS name')
Hmm. Maybe related with the python version. My python version is 3.9.1.
furkan@archlinux ~$ unimport foo.py                                          
✨ Congratulations there is no unused import in your project. ✨
furkan@archlinux ~$ unimport --version                                       
Unimport 0.7.1
furkan@archlinux ~$ python --version                                         
Python 3.9.1

```

**Comment by furkanonder** [comment]
> Hi @furkanonder !
> Thanks for checking.
> 
> I tried to make sure I was using the most recent version:
> 
> ```
> $ unimport --version
> Unimport 0.7.1
> $ python --version
> Python 3.6.2
> ```

Hmm. Maybe related with the python version. My python version is 3.9.1.
```
furkan@archlinux ~$ cat foo.py                                   
import os

print(f'{os.name} is the OS name')
furkan@archlinux ~$ unimport foo.py                                          
✨ Congratulations there is no unused import in your project. ✨
furkan@archlinux ~$ unimport --version                                       
Unimport 0.7.1
furkan@archlinux ~$ python --version                                         
Python 3.9.1

```

**Comment by miketheman** [comment]
Interesting! Would you mind if I tried to create a test case that reproduces this, and see if the tox test suite can confirm?

**Comment by miketheman** [comment]
Looks like an existing test case already exposes the f string use case: 
https://github.com/hakancelik96/unimport/blob/c9bd5de99bd8a5239d3dee2c3ff633979bb3ead2/tests/test_refactor.py#L169-L180

And I was able to reproduce this specifically on python 3.6.2, but then on 3.6.3 everything works fine.

Thanks for checking, and sorry to bother!
