### ISSUE TITLE
.gitignore support

### ISSUE THREAD

**Issue by hakancelik96** [hakancelik96/unimport#18]

**Comment by hakancelik96** [comment]
We currently have [two configuration settings](https://unimport.hakancelik.dev/#/?id=configuring-unimport), to include or exclude specified locations. What we want to do with this issue is to read and combine with the include, exclude setting if there is a .gitignore file.

You can do combine these two different configurations, the line starts at [158](https://github.com/hakancelik96/unimport/blob/master/unimport/__main__.py#l158) and ends at [169](https://github.com/hakancelik96/unimport/blob/master/unimport/__main__.py#l169), In the process done here, it is written to combine the settings from the console and the configuration setting.

**Comment by hadizakialqattan** [comment]
Good evening, If this issue hasn't solved yet, please assign it to me, I'm gonna solve it on the weekend.

**Comment by hadialqattan** [comment]
Fixed: #94

**Comment by hadialqattan** [comment]
New PR ~> #102 .
