### ISSUE TITLE
Don't depend on exact versions of dependencies

### ISSUE THREAD

**Issue by WouldYouKindly** [hakancelik96/unimport#194]
Hi.

Because `unimport` requires pathspec==0.8.1, it cannot be installed alongside the latest `black`, which requires patchspec>=0.9. The same applies to all other dependencies, e.g., I would like to update to `typing-extensions 3.10.0.2`, but I cannot cause `unimport` wants exactly `3.10.0.0`.

Could you please allow a broader range of versions in setup.py? This is actually a standard practice for python libraries/tools that one installs as a part of a project, see e.g., [pytest](https://github.com/pytest-dev/pytest/blob/main/setup.cfg#L44), [isort](https://github.com/PyCQA/isort/blob/main/pyproject.toml#L41), and [black](https://github.com/psf/black/blob/main/setup.py#L74).

**Comment by hakancelik96** [comment]
Hi,

Thank you for reporting the issue.
