### ISSUE TITLE
Option to suppress colourized output

### ISSUE THREAD

**Issue by pzelnip** [hakancelik96/unimport#199]
By default unimport will emit ascii colour codes in output, it'd be nice to have a way to suppress this.  I realize there's a check to see if the terminal supports colourized output, but there are also times when you want to explicitly suppress the colourization so that (as an example) you can locally redirect the output to a file and process that file via another script.

**Comment by hakancelik96** [comment]
Yes good point, I will work on that.

**Comment by hakancelik96** [comment]
Hi, can you try the version of 0.9.4?

check it out -> https://unimport.hakancelik.dev/#color

**Comment by pzelnip** [comment]
Works perfectly, thanks very much!

**Comment by hakancelik96** [comment]
You are welcome!
