### ISSUE TITLE
Ignore imports that shadow builtin names

### ISSUE THREAD

**Issue by jparise** [hakancelik96/unimport#45]
In our code base, we import some names from `builtins` as part of our Python 2+3 compatibility layer (using the [future](https://python-future.org/) library). These imports shadow the names of builtin symbols. For example:

```python
from builtins import next
from builtins import object
from builtins import range
```

_unimport_ flags these are unused imports, which is a false positive in our environment.

I can think of two possible solutions:

1. Teach _unimport_ to ignore these imported names (which are used by code within the rest of the module) even if they share the names of builtin functions.
2. Support an `--ignore` option so that we could explicitly tell _unimport_ to skip imports on a per-package basis (`builtins`, for this example).

**Comment by hakancelik96** [comment]
Between the options you have presented, I think, the first option is more appropriate and I sent a PR. Thank you for opening this issue
