### ISSUE TITLE
Support the `try ... except ImportError` pattern

### ISSUE THREAD

**Issue by jparise** [hakancelik96/unimport#46]
_unimport_ doesn't seem to recognize this common pattern:

```python
try:
    from django.core.handlers.wsgi import get_script_name
except ImportError:
    # django.VERSION < (1, 7)
    from django.core.handlers.base import get_script_name
```

If the initial import fails with `ImportError`, the second will be used. In this case, _unimport_ flags the first import attempt as unused.

**Comment by hakancelik96** [comment]
I think we should skip such imports. Because if it is controlled with ImportError, we do not know what purpose it is written for.
