### ISSUE TITLE
Imported exception types are flagged as unused

### ISSUE THREAD

**Issue by jparise** [hakancelik96/unimport#47]
If the imported type is only used in `except` statements, it will be flagged as unused. For example:

```python
from requests.exceptions import ConnectionError

try:
    pass
except ConnectionError:
    ConnectionError at foo.py:1
```

... produces:

```
ConnectionError at example.py:1
```

**Comment by hakancelik96** [comment]
In Python, [ConnectionError](https://docs.python.org/3/library/exceptions.html#ConnectionError) exists in built-in exceptions, and we ignore built-in objects directly.

for example;

```python
from x import ValueError

print(ValueError)
```

But wouldn't that be a bad use to give object the same names with built-in names.

Should we fix this issue, if we fix it, we will support this bad usage.
I am wondering what you are thinking.

**Comment by jparise** [comment]
Yes, it's unfortunate that (in this case) [Requests](https://2.python-requests.org/en/master/) has named their type with the same name as a built-in type. That being said, there isn't a nice workaround with annotating those imports with `#unimport: skip`, but that introduces a user education barrier that's not obvious to most.

#45 might be similar because it's also related to built-in names.

**Comment by hakancelik96** [comment]
Yes, both issues are the same. Okay let's close this issue and solve #45.

I think we should support this issue. I don't like telling people what to do, everybody is free.
