### ISSUE TITLE
Consider ignoring imports annotated with a `noqa` comment

### ISSUE THREAD

**Issue by jparise** [hakancelik96/unimport#48]
It would be nice if this tool recognize flake8-style `# noqa` comments. For example, if an import was annotated like this:

```python
import symbol  # noqa
```

... it wouldn't be flagged as unused even if it was never referenced.

**Comment by hakancelik96** [comment]
We use `#unimport:skip` comment to skip imports.
Example; 
```python
import x #unimport:skip
```

Would it be really nice to recognize flake8-style support? 

I am wondering what your thinking are @isidentical  @gkmngrgn

**Comment by jparise** [comment]
Thanks! I missed this in the documentation.

**Comment by hakancelik96** [comment]
**I am writing for newcomers.**

To give flake8-style `# noqa` comments support, you need to add [scan.py#L24](https://github.com/hakancelik96/unimport/blob/master/unimport/scan.py#L24) and then write the test for it in [test_scanner.py#L129](https://github.com/hakancelik96/unimport/blob/master/tests/test_scanner.py#L129)

**Comment by hakancelik96** [comment]
> Thanks! I missed this in the documentation.

@jparise Well I got it, would it be nice to recognize the `# noqa` comment support too? `#unimport:skip` additionally.

**Comment by jparise** [comment]
I think the existing unimport-specific comment syntax will be sufficient for our code base.

However, there are places where a link will need to be annotated with multiple kinds of comments in order for each tool to ignore it (flake8, unimport, maybe isort), so using a single “ignore this line” comment would still be nice (and `# noqa` would probably be the obvious common choice?).

**Comment by hakancelik96** [comment]
Okay I got it, and I did not know the meaning of noqa, I searched [here](https://github.com/PyCQA/pycodestyle/issues/476) and yes it would be much better.

so it will be like the example below.

```python
import x # noqa
```
