### ISSUE TITLE
Recognize `typing` imports used in typing comments

### ISSUE THREAD

**Issue by jparise** [hakancelik96/unimport#49]
It's common to import types from the `typing` package and only reference them in comments (for compatibility with Python 2). These imports are currently flagged as unused.

```python
from typing import Any
from typing import Tuple
from typing import Union

def function(a, b):
    # type: (Any, str) -> Union[Tuple[None, None], Tuple[str, str]]
```

**Comment by hakancelik96** [comment]
We don't support python 2 and if we support this case especially, we need to support other python 2 cases, but we only support python 3.6 or higher.

**Comment by hakancelik96** [comment]
Libcst supports python 3.0 and higher versions. With hard work, we can support maximum python 3.0 and higher.

**Comment by hakancelik96** [comment]
or we can use [parso](https://github.com/davidhalter/parso) for refactoring then we will support all python versions.

I don't know exactly and I'm not sure, but I'm researching.

**Comment by isidentical** [comment]
For 3.8+, python can detect/keep type comments inside of AST (see `ast.parse(type_comments=True)` option for details), for versions before that we either have to use typed_ast (which we don't actually need, but definitely better than this) or a little snippet to find used names inside of type comments (don't put this to repo directly, add more cases)

```py
import ast
import io
import tokenize
import contextlib

def iter_type_comments(content):
    buffer = io.StringIO(content)
    for token in tokenize.generate_tokens(buffer.readline):
        if token.type == tokenize.COMMENT:
            with contextlib.suppress(SyntaxError):
                functype = ast.parse(token.string[2:], mode="func_type")
                for m in ast.walk(ast.Module(functype.argtypes + [functype.returns])):
                    if isinstance(m, ast.Name) and isinstance(m.ctx, ast.Load):
                        yield m.id

print(*iter_type_comments("""
# (a, b) -> C
# () -> D
# (a) -> None
"""))
```

**Comment by hakancelik96** [comment]
As a result of the help of @isidentical, I wrote and tested the code and we can bring this feature only for python3.8.

Because [ast](https://docs.python.org/3.8/library/ast.html#ast.parse) has the type_comments flag only in python 3.8.

If we can find other, new solutions, we can add to other python versions too.

I will send a PR.

**Comment by jparise** [comment]
> As a result of the help of @isidentical, I wrote and tested the code and we can bring this feature only for python3.8.
> 
> Because [ast](https://docs.python.org/3.8/library/ast.html#ast.parse) has the type_comments flag only in python 3.8.
> 
> If we can find other, new solutions, we can add to other python versions too.

I think this sounds a like a good approach. We run our development tools on Python 3 but still support files with Python 2+3 compatibility, so this will work well for us. Thanks!
