### ISSUE TITLE
Consider file-wide skips

### ISSUE THREAD

**Issue by jparise** [hakancelik96/unimport#63]
isort has a comment syntax that tells it to skip the entire file: `# isort:skip_file`

It would be nice to support this in unimport via something like `# unimport:skip_file` so we wouldn't have to rely entirely on extending the `exclude` pattern or annotating each `import` line in a file with `# unimport:skip`.

**Comment by hakancelik96** [comment]
I examined this configuration of isort.

Isort looks at the pydoc of top of the file. If `# isort:skip_file` exists in pydoc as a string, It skips the file.

### How should we resolve this issue.

There are 4 different matches I found, If there is a match, that file will be skip the file, which match below should we choose.

- `# unimport:skip_file` anywhere in python file as a string.

- `# unimport:skip_file`  just on top of file as a string

- `# unimport:skip_file`  anywhere in a python file as a commment

- `# unimport:skip_file` just on top of file as a comment 

if these are wrong thoughts please let me know.

**Comment by jparise** [comment]
I think it should be in a comment at the top of the file, but I wouldn't want it to "fight" with the isort comment, because there are cases where we'd need to specify both.

**Comment by hakancelik96** [comment]
Actually there is no need to "fight" with the isort comment, I plan to do it as the example below.

```python

"""
maybe some doc string
"""

# or some comment 

# unimport:skip_file comment to skip this file by unimport

# start the first import statements

import x

and bla bla codes
.
.
.
.

```

Top of the file means that before import statements.

Do you think this approach is appropriate?

**Comment by hakancelik96** [comment]
Isort uses the following options

# isort: skip_file anywhere in the python file as a string.

and

# isort: skip_file as a comment anywhere in the python file

I think we should use the same approach.

**Comment by hakancelik96** [comment]
https://unimport.hakancelik.dev/#/?id=file-wide-skips
