### ISSUE TITLE
pre-commit hooks should not set verbose: true

### ISSUE THREAD

**Issue by asottile** [hakancelik96/unimport#72]
this is a debugging flag, I'm temporarily removing this from pre-commit.com for now, please fix this and revert this change:  https://github.com/pre-commit/pre-commit.com/commit/3bd42e2731e01d5e44464049c76b341d6e83c5cf

**Comment by hakancelik96** [comment]
Hi, I already fix this issue from the dev branch https://github.com/hakancelik96/unimport/commit/caf33ef31ed0ed60885de78ccb47ad3e7d1aedc7

**Comment by asottile** [comment]
it needs to be fixed on the default branch, that's what pre-commit.com and pre-commit use

**Comment by hakancelik96** [comment]
Okay I will merge it soon.

**Comment by hakancelik96** [comment]
I merged
