### ISSUE TITLE
Support for exit code different of zero when use arg --check

### ISSUE THREAD

**Issue by lacerdaeduardo** [hakancelik96/unimport#79]
Currently, when the argument `--check` is used with unimport and it complains about some file, it's actually exiting with code 0 instead of 1. In other words, there are no "errors".

![image](https://user-images.githubusercontent.com/1779871/88544228-737e1e80-cfef-11ea-9cf2-8e07b2253835.png)

So, when I use this in a CI pipeline, I have to implement a workaround like the one below to force it to fail the build on linter stage: 

```bash
unimport . --check --include-star-import | grep | grep -q "Congratulations there is no unused import in your project."
```

Please, it'd be nice if you guys add support to exit with code 1 when the --check founds some file that should be fixed. 😄

**Comment by isidentical** [comment]
I vaguely told this to @hakancelik96 back then but we kinda forgot about it, please feel free to send pull requests. Or we'll take care of it in the next version (since it is a really simple thing).

**Comment by furkanonder** [comment]
I add support for exit code and  some enhancements in __main__.py
