### ISSUE TITLE
Use the new pythonic module `pathlib` instead of `os.path`

### ISSUE THREAD

**Issue by gkmngrgn** [hakancelik96/unimport#8]
Who can take a look at this issue? @hakancelik96 @isidentical?

https://github.com/hakancelik96/unimport/pull/4/files/183645ee3845b85978b1751506ecb4e61a4bbfca#diff-17648ebdb7f13b2f63c236a55af216ad

**Comment by isidentical** [comment]
Unfortunately, not me :/
