### ISSUE TITLE
Update Docs [ wrong url addresses]

### ISSUE THREAD

**Issue by hakancelik96** [hakancelik96/unimport#88]
There are some misspelled addresses in [CONTRIBUTING](https://github.com/hakancelik96/unimport/blob/master/docs/CONTRIBUTING.md) file.

The AUTHORS.md address should be https://github.com/hakancelik96/unimport/blob/master/docs/AUTHORS.md.

The CHANGELOG.md address should be https://github.com/hakancelik96/unimport/blob/master/docs/CHANGELOG.md

**Comment by abdulniyaspm** [comment]
@hakancelik96 Just to be clear, we need to remove the broken links [CONTRIBUTING.md](https://github.com/hakancelik96/unimport/blob/master/docs/README.md#contributing) and [CHANGELOG.md ](https://github.com/hakancelik96/unimport/blob/master/docs/README.md#changelog) from the [README](https://github.com/hakancelik96/unimport/blob/master/docs/README.md)?

**Comment by hakancelik96** [comment]
I think we should remove them, these are seems unnecessary.

**Comment by abdulniyaspm** [comment]
So that idea is to remove [CONTRIBUTING](https://unimport.hakancelik.dev/#/?id=contributing) and [CHANGELOG](https://unimport.hakancelik.dev/#/?id=changelog) as we already have separate tabs for [CONTRIBUTING](https://unimport.hakancelik.dev/#/CONTRIBUTING) and [CHANGELOG](https://unimport.hakancelik.dev/#/CHANGELOG)?

**Comment by hakancelik96** [comment]
> So the idea is to remove [CONTRIBUTING](https://unimport.hakancelik.dev/#/?id=contributing) and [CHANGELOG](https://unimport.hakancelik.dev/#/?id=changelog) from [here](https://github.com/hakancelik96/unimport/blob/master/docs/README.md#contributing) as we already have separate tabs for [CONTRIBUTING](https://unimport.hakancelik.dev/#/CONTRIBUTING) and [CHANGELOG](https://unimport.hakancelik.dev/#/CHANGELOG)?

Yes, but It must be fixed [CONTRIBUTING.md](https://github.com/hakancelik96/unimport/blob/master/docs/CONTRIBUTING.md) file too. please read the issue again, I  updated.

**Comment by hadialqattan** [comment]
I'll solve this issue!

**Comment by hadialqattan** [comment]
Fixed: #96

**Comment by abdulniyaspm** [comment]
@hadialqattan This will fix the broken links in the  CONTRIBUTING.md  file but introduce 404 Error in CHANGELOG.md and AUTHORS.md links the [Docs](https://unimport.hakancelik.dev/#/CONTRIBUTING?id=the-final-step). I am not sure which file should we update to fix this issue.

**Comment by hadialqattan** [comment]
@abdulniyaspm You're right!
@hakancelik96 I'm sorry about that, I'm gonna reopen the PR!
