### ISSUE TITLE
Low test coverage.

### ISSUE THREAD

**Issue by hadialqattan** [hakancelik96/unimport#89]
I'm gonna improve test coverage!
Please assign this issue to me!

**Comment by hakancelik96** [comment]
Hi, thank you for your interest and work.

It doesn't matter that the coverage ratio is high, It is much more important to make sure that the test of each case is written, please put this more first.

**Comment by hadizakialqattan** [comment]
In the first place, it's my priority, but it would be great to have %99-100 of code coverage.

**Comment by hakancelik96** [comment]
> In the first place, it's my priority, but it would be great to have %99-100 of code coverage.

I agree with you

**Comment by hadialqattan** [comment]
https://github.com/hakancelik96/unimport/blob/098eb5f3da3ca3213c546e9806806d33b384fbf1/unimport/refactor.py#L135

I'm wondering why this line exists!
I can't figure out in which case this line may be executed!

**Comment by hadialqattan** [comment]
Fixed: #93

**Comment by hakancelik96** [comment]
> https://github.com/hakancelik96/unimport/blob/098eb5f3da3ca3213c546e9806806d33b384fbf1/unimport/refactor.py#L135
> 
> I'm wondering why this line exists!
> I can't figure out in which case this line may be executed!

I guess I wrote that if the get_star_imp function returns None, leave_ImportFrom function returns original_node, but now I have examined it, there is no such possibility, so it was an unnecessary line. Because we take all-star imports as unused imports and then offer a suggestion object instead of a star.

**Comment by hadialqattan** [comment]
So, I'm gonna remove this line, then I think it's a good time to review the PR (#93 )
